site_name: ReadyML
site_description: ReadyML makes trained Machine Learning models ready to consume with minimum effort.
site_url: https://github.com/houseofai/readyml
repo_url: https://github.com/houseofai/readyml

nav:
    - 'Home': index.md
    - 'Models': models.md

theme: readthedocs
